apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanslogs-cert
  namespace: vanslogs
spec:
  secretName: my-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vanslogs.store
  dnsNames:
  - vanslogs.store
